remote_theme: just-the-docs/just-the-docs

# Define Jekyll collections
collections:
  accounts:
    permalink: "/:collection/:path/"
    output: true
  api:
    permalink: "/:collection/:path/"
    output: true
just_the_docs:
  collections:
    accounts:
      name: Accounts
      nav_exclude: false
      nav_fold: false
      search_exclude: false
    api:
      name: REST API
      nav_exclude: false
      nav_fold: true
      search_exclude: true


# this is needed for the sitmap generator plugin
url: "https://receptionstar.com/docs"


# Set a path/url to a logo that will be displayed instead of the title
#logo: "/assets/images/just-the-docs.png"

# Enable or disable the site search
# Supports true (default) or false
search_enabled: true
search:
  # Split pages into sections that can be searched individually
  # Supports 1 - 6, default: 2
  heading_level: 2
  # Maximum amount of previews per search result
  # Default: 3
  previews: 2
  # Maximum amount of words to display before a matched word in the preview
  # Default: 5
  preview_words_before: 3
  # Maximum amount of words to display after a matched word in the preview
  # Default: 10
  preview_words_after: 3
  # Set the search token separator
  # Default: /[\s\-/]+/
  # Example: enable support for hyphenated search words
  tokenizer_separator: /[\s/]+/
  # Display the relative url in search results
  # Supports true (default) or false
  rel_url: true
  # Enable or disable the search button that appears in the bottom right corner of every page
  # Supports true or false (default)
  button: false

# Enable or disable heading anchors
heading_anchors: true

# Aux links for the upper right navigation
aux_links:
  "Reception Star":
    - "//receptionstar.com"
# Makes Aux links open in a new tab. Default is false
aux_links_new_tab: false

# Sort order for navigation links
# nav_sort: case_insensitive # default, equivalent to nil
nav_sort: case_insensitive # Capital letters sorted before lowercase

# Include links to parent and sibling pages when showing the automatic TOC. Default is false
nav_next_prev: true
# The default arrows can be changed to other characters or words
# nav_prev_text: "&larr;"
# nav_up_text:   "&uarr;"
# nav_next_text: "&rarr;"

# External navigation links
nav_external_links:
  - title: ReceptionStar.com
    url: https://reeptionstar.com

# Caching navigation links
# nav_cache: true

# Footer content
# appears at the bottom of every page's main content

# Back to top link
back_to_top: true
back_to_top_text: "Back to top"

footer_content: "Copyright &copy; 2014-2022 Reception Star."

# Footer last edited timestamp
last_edit_timestamp: false # show or hide edit time - page must have `last_modified_date` defined in the frontmatter
last_edit_time_format: "%b %e %Y at %I:%M %p" # uses ruby's time format: https://ruby-doc.org/stdlib-2.7.0/libdoc/time/rdoc/Time.html



# Footer "Edit this page on GitHub" link text
gh_edit_link: false # show or hide edit this page link
gh_edit_link_text: "Edit this page on GitHub"
gh_edit_repository: "https://github.com/turgs/ReceptionStar" # the github URL for your repo
gh_edit_branch: "master" # the branch that your docs is served from
# gh_edit_source: docs # the source that your files originate from
gh_edit_view_mode: "tree" # "tree" or "edit" if you want the user to jump into the editor immediately

# Color scheme currently only supports "dark", "light"/nil (default), or a custom scheme that you define
color_scheme: light
# To add a button to switch all pages to a different scheme: default: nil (no toggle button)
toggle_color_scheme: dark

# To display the toggle button only on one page: default: nil (display on all pages)
# toggle_page_url: "/"

# To toggle automatically when the system mode preference changes. default: nil (manual toggle)
toggle_auto_mode: true
# To set the button text for toggling and reverting:
# toggle_text_1: "&rarr; &#x26ab;" # default: "&rarr; Dark Mode"
# toggle_text_2: "&rarr; &#x26ab;" # default: "&rarr; Light Mode"

# Callouts
# 
# The title of a callout is optional. It is rendered in uppercase.
# 
# Each kind of callout has a color, used for the callout bar, the title, and the background.
# Predefined colors: grey-lt, grey-dk, purple, blue, green, yellow, red.
# If you use another color, you should define its levels (000, 100, 200, 300) in _sass/custom/custom.scss.
#
# The default is for callout backgrounds to have a lower color level than the bars and titles.
# The value of `callouts_level` is either `quiet` or `loud`:
# `loud` increases the saturation and lightness of the backgrounds.
# The default for `callouts_level` is `quiet` when using the `light` or custom color schemes,
# and `loud` when using the `dark` color scheme.
# 
# Examples (not provided by default):
# 
# callouts:
#   admonition:
#     # title:
#     color: grey-lt
#   attention:
#     title: Attention
#     color: purple
#   caution:
#     title: Caution
#     color: yellow
#   custom:
#     title: Custom
#     color: pink
#     opacity: 0.3
#   danger:
#     title: Danger
#     color: red
#   error:
#     title: Error
#     color: red
#   highlight:
#     color: yellow
#     opacity: 0.5
#   hint:
#     title: Hint
#     color: grey-dk
#   important:
#     title: Important
#     color: green
#   note:
#     title: Note
#     color: blue
#   tip:
#     title: Tip
#     color: grey-dk
#   warning:
#     title: Warning
#     color: red

# https://pages.github.com/versions/
plugins:
  - jekyll-seo-tag
  - jekyll-include-cache
  - jekyll-sitemap

kramdown:
  syntax_highlighter_opts:
    block:
      line_numbers: false

compress_html:
  clippings: all
  comments: all
  endings: all
  startings: []
  blanklines: false
  profile: false
  # ignore:
  #   envs: all

